import math as m
import numpy as np


def get_isoval_by_ptbins(pts, isos, *, 
                         ptbins=None):
    
    """ 
    Bin the isos based on the pts.
    The current pt bins are fixed between 0 to 150 GeV.
    The ptbins functionality is not implemented yet.

    Arguments
    ---------
    * pts: list(events) of list(electrons) of pt values
    * isos: same as pt but iso values. Should have a one to one correspondence with pts
    
    Returns
    -------
    A mapping of pt bin low edge to an array of isolation values
    
    Issues
    ------
    The customised ptbins have not been implemented.
    The pts and isos can be potentially generalised to other variables.
    """

    ptmax = 70
    iso_pt_binned = {i: [] for i in range(ptmax+1)}
    if ptbins:
        # At a later stage modify to adapt iso_pt_binned from ptbins
        raise RuntimeError("The option with ptbins not yet supported.")
    
    for pte, isoe in zip(pts, isos):
        for pt, iso in zip(pte, isoe):
            idx = m.floor(pt)
            idx = idx if idx < ptmax else ptmax
            iso_pt_binned[idx].append(iso)

    return iso_pt_binned


def get_isovals_for_sigpercentiles(pts, isos, percentiles, *,
                                   ptbins=None):
    
    """
    Generate the iso value corresponding a specific percentile
    in signal for each pt bin.

    Arguments
    ---------
    * pts: list(events) of list(electrons) of pt values
    * isos: same as pt but iso values. Should have a one to one correspondence with pts
    * percentiles: A list of percentile values.
    
    Returns
    -------
    A list of mapping of ptbin to isolation value. Each entry in the list corresponds
    to the percentiles list.
    
    Issues
    ------
    The customised ptbins have not been implemented.
    The pts and isos can be potentially generalised to other variables.
    """

    iso_pt_binned = get_isoval_by_ptbins(pts, isos, ptbins=ptbins)

    isovals_for_sigpercentiles = []
    for percentile in percentiles:
        isovals_for_sigpercentile = {k: (np.nanpercentile(v,
            percentile) if len(v) > 0 else np.nan) for k, v in iso_pt_binned.items()}
        isovals_for_sigpercentiles.append(isovals_for_sigpercentile) 

    return isovals_for_sigpercentiles


def get_fpr_by_sigpercentiles(pts, isos, sig_percentiles, *,
                              ptbins=None):
    
    """
    Generate the false positive rate correpsonding to the isolation value for a specific 
    signal percentile. In single electron events, this will correspond to rate.
    
    Arguments
    ---------
    * pts: list(events) of list(electrons) of pt values
    * isos: same as pt but iso values. Should have a one to one correspondence with pts
    * sig_percentiles: A list of mapping of ptbins to isolation values. Output generated by 
                       get_isovals_for_sigpercentiles()
    
    Returns
    -------
    A list of mapping of ptbin to fpr value. Each entry in the list corresponds
    to the percentiles list input to get_isovals_for_sigpercentiles.
    
    Issues
    ------
    The customised ptbins have not been implemented.
    The pts and isos can be potentially generalised to other variables.
    """
    biso_pt_binned = get_isoval_by_ptbins(pts, isos, ptbins=ptbins)

    fpr_by_sigpercentiles = []
    for sig_percentile in sig_percentiles:
        fpr_by_sigpercentile = {k: (np.sum(v < sig_percentile[k])*100/len(v) if (sig_percentile is not np.nan and len(v) > 0) else np.nan) for k, v in biso_pt_binned.items()}
        fpr_by_sigpercentiles.append(fpr_by_sigpercentile)

    return fpr_by_sigpercentiles